# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
name: cv-commit-publish
on:
  push:
    branches: [main, master]
  schedule:
    - cron: "0 0 * * 0"

jobs:
  cv-commit-publish:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Install system dependencies
        run: |
          sudo apt-get install libcurl4-openssl-dev
      - name: Install/Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: '2.13' # The pandoc version to download (if necessary) and use.
      - run: echo "# Test" | pandoc -t html
      
      - name: Setup TinyTex 
        uses: r-lib/actions/setup-tinytex@v2
      - run: tlmgr --version

      - name: Install/Setup R packages
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 2

      - name: Grab CV
        run: |
          curl https://github.com/mikecuoco/curriculum-vitae/raw/master/main.pdf > cv.pdf
          
      - name: Render Rmarkdown
        run: |
          Rscript -e "rmarkdown::render('index.Rmd')"

      - name: Commit results
        run: |
          git config --global user.email "mcuoco12@gmail.com"
          git config --global user.name "mikecuoco"
          git add index.html || echo "No changes to add"
          git commit -m 'Add updated CV to website' || echo "No changes to commit"
          git push origin || echo "No changes to commit"