# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
name: Update CV, Build, Deploy
on:
  push:
    branches: [main, master]
  repository_dispatch:
    types: [build-cv]

jobs:
  UpdateCV-Build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: echo ${{ github.event.client_payload.sha }}
      
      - name: Install system dependencies
        run: |
          sudo apt-get -qqy update --fix-missing
          sudo apt-get install libcurl4-openssl-dev
      - name: Install/Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2
      - run: echo "# Test" | pandoc -t html
      
      - name: Setup TinyTex 
        uses: r-lib/actions/setup-tinytex@v2
      - run: tlmgr --version

      - name: Install/Setup R packages
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 2

      - name: Grab CV
        run: |
          wget https://github.com/mikecuoco/curriculum-vitae/raw/master/main.pdf && mv main.pdf cv.pdf
          
      - name: Render Rmarkdown
        run: |
          Rscript -e "rmarkdown::render('index.Rmd')"

      - name: Commit results
        run: |
          git config --global user.email "mcuoco12@gmail.com"
          git config --global user.name "mikecuoco"
          git add cv.pdf index.html || echo "No changes to add"
          git commit -m 'Add updated CV to website' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
  Deploy:
    needs:
      - UpdateCV-Build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: '.'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: false
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1